# Generated by Django 4.2.1 on 2023-05-16 15:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpostviews",
            options={"verbose_name_plural": "Blog post views"},
        ),
        migrations.AlterField(
            model_name="blogimagelink",
            name="image",
            field=blog.models.WEBPField(
                default="", upload_to=blog.models.image_folder, verbose_name="image"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=blog.models.WEBPField(
                default="",
                upload_to=blog.models.image_folder,
                verbose_name="cover_image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpostviews",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
